"""Scaffold generation for ``hiveplane wrap`` (M31-05, M31-06).

Given a :class:`~hiveplane.wrap.detect.Detection`, render the files an operator
needs to onboard an existing app: a workload manifest draft (``uncertified``), an
adapter scaffold that imports the app as a library, a corpus template, and a
short README. Nothing here registers, certifies, or runs the app; the scaffold is
inert until an operator registers and certifies it.
"""

from __future__ import annotations

import yaml

from hiveplane.wrap.detect import Detection

_GUIDE = "docs/ADAPTERS.md"


def _slug(detection: Detection) -> str:
    return detection.source_root.name.lower().replace("_", "-") or "wrapped-agent"


def render_workload_yaml(detection: Detection) -> str:
    """Render a draft workload manifest for the detected app."""
    assert detection.framework is not None
    manifest = {
        "apiVersion": "hiveplane/v1",
        "kind": "AgentWorkload",
        "metadata": {
            "name": _slug(detection),
            "owner": "REPLACE_ME",
            "description": f"Wrapped {detection.framework} application.",
        },
        "spec": {
            "runtime": {
                "adapter": detection.framework,
                "entrypoint": "adapter_scaffold:entrypoint",
                "adapter_contract": "2",
            },
            "model": {
                "strategy": "fixed",
                "identity": {
                    "provider": "REPLACE_ME",
                    "family": "REPLACE_ME",
                    "version": "REPLACE_ME",
                },
            },
            "certification": {
                "benchmark_corpus": "corpus",
                "status": "uncertified",
            },
            "budget": {
                "per_run_usd": 0.50,
                "per_day_usd": 5.00,
                "per_team_usd": 50.00,
            },
            "sandbox": {
                "enabled": True,
                "resource_caps": {
                    "memory_mb": 512,
                    "cpu_cores": 1.0,
                    "wall_clock_s": 300,
                },
                "egress": {"allow": [], "mode": "restricted"},
            },
        },
    }
    header = (
        "# Generated by `hiveplane wrap` — a draft, uncertified manifest.\n"
        "# Registration and certification are explicit, separate steps.\n"
    )
    return header + yaml.safe_dump(manifest, sort_keys=False)


def render_scaffold(detection: Detection) -> str:
    """Render the adapter scaffold that imports the app as a library."""
    assert detection.entrypoint is not None
    module, _, name = detection.entrypoint.partition(":")
    return (
        '"""Generated by `hiveplane wrap`.\n\n'
        "Inert until registered and certified: importing this module only\n"
        "re-exports the detected entrypoint so an adapter can drive it. It never\n"
        "modifies the source application.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"from {module} import {name} as entrypoint  # noqa: F401\n"
    )


def render_corpus_template(detection: Detection) -> str:
    """Render a starter benchmark corpus template."""
    name = _slug(detection)
    return (
        f"# Starter corpus template for {name}. Replace the placeholder task.\n"
        f"id: {name}-corpus\n"
        "version: 1\n"
        "tasks:\n"
        "  - id: pos-001\n"
        "    name: REPLACE_ME\n"
        "    input:\n"
        '      prompt: "REPLACE_ME"\n'
        "    expected:\n"
        '      outcome: "REPLACE_ME"\n'
        "    check:\n"
        "      type: exact_match\n"
        "      field: outcome\n"
        '      value: "REPLACE_ME"\n'
        "    critical: false\n"
        "    timeout_seconds: 30\n"
    )


def render_readme(detection: Detection) -> str:
    """Render a short README pointing at the bring-your-own-agent guide."""
    assert detection.entrypoint is not None
    return (
        f"# Wrapped {detection.framework} app\n\n"
        f"Detected entrypoint: `{detection.entrypoint}`\n\n"
        "Generated files are inert drafts. Next steps:\n\n"
        "1. Edit `workload.yaml` (owner, model identity, tools, budget).\n"
        "2. Replace the placeholder task in `corpus.template.yaml` and point\n"
        "   `spec.certification.benchmark_corpus` at a real corpus.\n"
        f"3. Register the manifest and certify it — see `{_GUIDE}`.\n\n"
        "`hiveplane wrap` never modifies the source application.\n"
    )


def render_files(detection: Detection) -> dict[str, str]:
    """Render every generated file, keyed by file name."""
    return {
        "workload.yaml": render_workload_yaml(detection),
        "adapter_scaffold.py": render_scaffold(detection),
        "corpus.template.yaml": render_corpus_template(detection),
        "README.md": render_readme(detection),
    }
